### ISSUE TITLE
Incorrect font parameter description in documentation for add_text

### ISSUE THREAD

**Issue by nebukadnezar** [pytroll/pydecorate#10]
The font parameter for add_text does not take a font object as parameter as described by the documentation, but rather a string object describing the path to the font to use.

Font parameters such as size are then passed as additional optional parameters in the add_text call. An example for correct usage would be:

`dc.add_text("IR Temperature [C]", font="/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf", font_size=12, height=25)`

**Comment by djhoese** [comment]
This should be fixed in the next release (0.3) and it should have been addressed by #11. I'll close this for now assuming it is fixed. If it is still a problem then we can reopen.
