### ISSUE TITLE
pydecorate.DecoratorAGG: How to put text/colorbar outside of image and control width of colorbar. 

### ISSUE THREAD

**Issue by randomusername5** [pytroll/pydecorate#17]
I am working with pydecorate to add text and colorbar to images . I am working with this tutorial:
[https://pydecorate.readthedocs.io/en/latest/usage.html](url)
I am using this code:
```Python
from PIL import Image
from pydecorate import DecoratorAGG
import aggdraw
from trollimage.colormap import rdbu
import matplotlib.pyplot as plt

filepath = r'path\to\file.tif
img = Image.open(filepath)

dc = DecoratorAGG(img)
dc.write_vertically() 
dc.align_left()

font=aggdraw.Font("black", r'C:\Windows\Fonts\times.ttf', size = 115)
dc.add_text(
    'text line 1\nline 2 or text\nThis is also text', 
            font = font)
dc.add_scale(rdbu, extend = True)

imgplot = plt.imshow(img) # image will not display in plots window.
```
This creates text and a colorbar like I want, but the width of the colorbar seems to be dictated by the width of the text above it. Is there some way to manually set the width of the colorbar? 
Also, is there some way to display the colorbar next to the image, as opposed to on the edge of the image? Should I do this by simply adding a border?
Thanks for your help.

**Comment by djhoese** [comment]
It is hard to tell from the source code (I didn't write this logic). You can find the function here:

https://github.com/pytroll/pydecorate/blob/a49e1b8ce3f318999277b12bfb4ee654a1247ff5/pydecorate/decorator_base.py#L387

There is no way as far as I know to put the colorbar outside the image, but maybe with what you/I learn to solve the width issue will help figure that out.

Things to try:

1. What if you add the scale before the text? My guess is adding the text is setting some property for the text that is not being overwritten/reset before the colorbar is added.
2. Try doing `print(dc.style)` before adding the text, after adding the text, and after adding the scale and let me know what the output is.
3. Based on the code it looks like you should be able to specify `cursor=(float1, float2)` and/or `margins=(float1, float2)` and change the location or size of the colorbar.

**Comment by randomusername5** [comment]
Hey @djhoese thank you for the fast reply. Adding the scale before the text makes the colorbar very "skinny", with width independent of text. This may be due to the large image size. 
On the ```print(dc.style)```  you had mentioned:
```Python
# before text: 
print(dc.style)
{'cursor': [0, 0], 'margins': [5, 5], 'height': 60, 'width': 60, 
'propagation': [0, 1], 'newline_propagation': [1, 0], 'alignment': [0.0, 0.0], 
'bg': 'white', 'bg_opacity': 127, 'line': 'black', 'line_width': 1, 
'line_opacity': 255, 'outline': None, 'outline_width': 1, 'outline_opacity': 255, 
'fill': 'black', 'fill_opacity': 255, 'font': None, 'font_size': 16, 
'start_border': [0, 0], 'extend': False, 'tick_marks': 1.0, 
'minor_tick_marks': 0.5, 'unit': None}

# After adding text: 
print(dc.style)
{'cursor': [0, 406], 'margins': [5, 5], 'height': 406, 'width': 815, 
'propagation': [0, 1], 'newline_propagation': [1, 0], 'alignment': [0.0, 0.0], 
'bg': 'white', 'bg_opacity': 127, 'line': 'black', 'line_width': 1, 'line_opacity': 255, 
'outline': None, 'outline_width': 1, 'outline_opacity': 255, 'fill': 'black', 
'fill_opacity': 255, 'font': <Font object at 0x00000283058D3810>, 
'font_size': 16, 'start_border': [0, 0], 'extend': False, 
'tick_marks': 1.0, 'minor_tick_marks': 0.5, 'unit': None}

# after adding scale:
print(dc.style)
{'cursor': [0, 406], 'margins': [5, 5], 'height': 5594, 'width': 815, 
'propagation': [0, 1], 'newline_propagation': [1, 0], 'alignment': [0.0, 0.0], 
'bg': 'white', 'bg_opacity': 127, 'line': 'black', 'line_width': 1, 
'line_opacity': 255, 'outline': None, 'outline_width': 1, 
'outline_opacity': 255, 'fill': 'black', 'fill_opacity': 255, 
'font': <Font object at 0x00000283058D3810>, 'font_size': 16, 
'start_border': [0, 0], 'extend': True, 'tick_marks': 1.0, 
'minor_tick_marks': 0.5, 'unit': None}
```
It seems the only changes were to 'cursor', 'height', 'width', then things specific to the font like 'font'. I will work on the 3rd 'Thing to try'  over the weekend. Will post a comment later in the hopes that someone else may find it useful.

**Comment by djhoese** [comment]
So theoretically if you specify the kwarg `cursor=[0, 0]` in your scale creation it *should* make it just as skinny as when you add the scale first. Again, theoretically.

**Comment by randomusername5** [comment]
The cursor kwarg seems to set the position of the top right corner of the colorbar. For instance:
```Python
dc.write_vertically()
dc.align_right()
dc.add_scale(spectral, extend = True, cursor = [6850, 388]) # cursor = [x, y]
# note that setting the cursor works better if text is added first.
```
This puts the colorbar on the right side of the image, and effectively limits its width by putting 850 of the 1000 pixel wide colorbar outside of the image.  
On `margins=(float1, float2)`:
Perhaps unsurprisingly, the `margins` kwarg adjusts the margins (in pixels) around the colorbar... This could be useful later but is not needed in what I am trying to do. For now, I can leave the colorbar inside of the image.
