### ISSUE TITLE
Add logo incompat with Pillow v10

### ISSUE THREAD

**Issue by zmoon** [pytroll/pydecorate#47]
Due to this line

https://github.com/pytroll/pydecorate/blob/4d21d613fdd38beffcef3c7fd2dfb7e37f49c7cd/pydecorate/decorator_base.py#L357

(`Image.ANTIALIAS` [was removed](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants).)

Exception:
```
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by djhoese** [comment]
Hm thanks for filing this. This makes me think our CI isn't testing the logo parts of the code. How would you feel about making a pull request to fix this? Our pycoast package has similar incompatibilities with pillow 10 so we're working on those too.

**Comment by zmoon** [comment]
Sure, happy to give it a go.
